name: aurora_mjo
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - xarray
  - dask
  - bottleneck
  - netcdf4
  - h5netcdf
  - cfgrib
  - cdsapi
  - matplotlib
  - jupyterlab
  - pre-commit
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - microsoft-aurora