name: aurora_mjo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.8 # bouchet cuda version

  - numpy
  - pandas
  - xarray
  - dask
  - bottleneck
  - netcdf4
  - h5netcdf
  - cfgrib  
  - cdsapi  

  - matplotlib
  - jupyterlab
  - pre-commit

  - pip:
    - microsoft-aurora